/**
 * Internal Electron IPC channel allowlist (078 T028).
 * Renderer never sees these strings through preload.
 */

export const IPC = {
  appStatus: "lp:app:status",
  appShutdown: "lp:app:shutdown",
  sessionCreateInteractive: "lp:session:createInteractive",
  sessionResumeInteractive: "lp:session:resumeInteractive",
  sessionReleaseInteractive: "lp:session:releaseInteractive",
  sessionList: "lp:session:list",
  sessionHistory: "lp:session:history",
  sessionRename: "lp:session:rename",
  sessionSetStarred: "lp:session:setStarred",
  sessionDelete: "lp:session:delete",
  sessionFork: "lp:session:fork",
  projectList: "lp:project:list",
  projectCreate: "lp:project:create",
  projectRename: "lp:project:rename",
  projectRemove: "lp:project:remove",
  projectAssignSession: "lp:project:assignSession",
  workspaceList: "lp:workspace:list",
  workspaceChooseAndBind: "lp:workspace:chooseAndBind",
  workspaceChooseAndRelink: "lp:workspace:chooseAndRelink",
  workspaceRemove: "lp:workspace:remove",
  workspaceRevalidate: "lp:workspace:revalidate",
  interactionSubmit: "lp:interaction:submit",
  interactionCancel: "lp:interaction:cancel",
  interactionAnswerApproval: "lp:interaction:answerApproval",
  interactionAnswerQuestion: "lp:interaction:answerQuestion",
  inspectionGet: "lp:inspection:get",
  agentControlsGet: "lp:agentControls:get",
  capabilitiesList: "lp:capabilities:list",
  capabilitiesInvokeAction: "lp:capabilities:invokeAction",
  auditList: "lp:audit:list",
  costGet: "lp:cost:get",
  capabilityMcpList: "lp:capability:mcpList",
  capabilityMcpGet: "lp:capability:mcpGet",
  capabilityMcpUpsert: "lp:capability:mcpUpsert",
  capabilityMcpReconnect: "lp:capability:mcpReconnect",
  capabilityMcpDelete: "lp:capability:mcpDelete",
  capabilitySkillList: "lp:capability:skillList",
  capabilitySkillGet: "lp:capability:skillGet",
  capabilitySkillWrite: "lp:capability:skillWrite",
  capabilitySkillImport: "lp:capability:skillImport",
  capabilitySkillDelete: "lp:capability:skillDelete",
  capabilityMemoryList: "lp:capability:memoryList",
  capabilityMemoryGet: "lp:capability:memoryGet",
  capabilityMemoryWrite: "lp:capability:memoryWrite",
  capabilityMemoryDelete: "lp:capability:memoryDelete",
  governanceScheduleList: "lp:governance:scheduleList",
  governanceScheduleGet: "lp:governance:scheduleGet",
  governanceScheduleUpsert: "lp:governance:scheduleUpsert",
  governanceScheduleEnable: "lp:governance:scheduleEnable",
  governanceScheduleDisable: "lp:governance:scheduleDisable",
  governanceScheduleRunNow: "lp:governance:scheduleRunNow",
  governanceScheduleDelete: "lp:governance:scheduleDelete",
  governanceContextList: "lp:governance:contextList",
  governanceContextGet: "lp:governance:contextGet",
  governanceContextUpsert: "lp:governance:contextUpsert",
  governanceContextBind: "lp:governance:contextBind",
  governanceContextDelete: "lp:governance:contextDelete",
  governanceModelDefaultGet: "lp:governance:modelDefaultGet",
  governanceModelDefaultSet: "lp:governance:modelDefaultSet",
  governanceModelDefaultClear: "lp:governance:modelDefaultClear",
  commandExecute: "lp:command:execute",
  backupDescribe: "lp:backup:describe",
  backupCreate: "lp:backup:create",
  restoreValidate: "lp:restore:validate",
  restoreCommit: "lp:restore:commit",
  restoreCancel: "lp:restore:cancel",
  /**
   * Provider settings (Unit A). Main owns the credential; only a public view of
   * it ever answers `providersGet`.
   */
  providersGet: "lp:providers:get",
  providersSave: "lp:providers:save",
  providersClear: "lp:providers:clear",
  providersRestart: "lp:providers:restart",
  providersCatalog: "lp:providers:catalog",
  /** Main -> renderer push (not invoke). */
  statusEvent: "lp:app:statusEvent",
  interactionEvent: "lp:interaction:event",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
