"""The Runtime Event Bus vocabulary, serialization, and sequencing
(contracts/runtime-events.md).
"""

from loopplane.events.emitter import EventEmitter, EventSink
from loopplane.events.envelope import (
    SCHEMA_VERSION,
    ApprovalRequestedEvent,
    ApprovalRequestedPayload,
    ApprovalResolvedEvent,
    ApprovalResolvedPayload,
    AssistantOutputIncrementEvent,
    AssistantOutputIncrementPayload,
    AssistantReasoningIncrementEvent,
    AssistantReasoningIncrementPayload,
    DiagnosticEvent,
    DiagnosticPayload,
    Question,
    QuestionAnsweredEvent,
    QuestionAnsweredPayload,
    QuestionAskedEvent,
    QuestionAskedPayload,
    ReplayCompletedEvent,
    ReplayCompletedPayload,
    ReplayStartedEvent,
    ReplayStartedPayload,
    RunTerminatedEvent,
    RunTerminatedPayload,
    RuntimeEvent,
    TerminationReason,
    ToolCallCompletedEvent,
    ToolCallCompletedPayload,
    ToolCallStartedEvent,
    ToolCallStartedPayload,
    TurnCompletedEvent,
    TurnCompletedPayload,
    UserInputEvent,
    UserInputPayload,
)
from loopplane.events.sequencer import EventSequencer
from loopplane.events.serde import deserialize_event, serialize_event

__all__ = [
    "SCHEMA_VERSION",
    "ApprovalRequestedEvent",
    "ApprovalRequestedPayload",
    "ApprovalResolvedEvent",
    "ApprovalResolvedPayload",
    "AssistantOutputIncrementEvent",
    "AssistantOutputIncrementPayload",
    "AssistantReasoningIncrementEvent",
    "AssistantReasoningIncrementPayload",
    "DiagnosticEvent",
    "DiagnosticPayload",
    "EventEmitter",
    "EventSequencer",
    "EventSink",
    "Question",
    "QuestionAnsweredEvent",
    "QuestionAnsweredPayload",
    "QuestionAskedEvent",
    "QuestionAskedPayload",
    "ReplayCompletedEvent",
    "ReplayCompletedPayload",
    "ReplayStartedEvent",
    "ReplayStartedPayload",
    "RunTerminatedEvent",
    "RunTerminatedPayload",
    "RuntimeEvent",
    "TerminationReason",
    "ToolCallCompletedEvent",
    "ToolCallCompletedPayload",
    "ToolCallStartedEvent",
    "ToolCallStartedPayload",
    "TurnCompletedEvent",
    "TurnCompletedPayload",
    "UserInputEvent",
    "UserInputPayload",
    "deserialize_event",
    "serialize_event",
]
